# NumPy

- NumPy arrays are the main way we will use NumPy module.
- Numpy arrays essentailly comes as vectors and matrices.
- vectors are 1-d arrays
- matrices are 2-d but can have single row or col.

### methods of numpy
- use tab to find out all
- some encountered are
    - array()
    - arange()
    - zeros()
    - ones
    - linspace --> returns number of numbers(metioned as third parameter) evenly spaced numbers b/w start and stop.
    - 

# NumPy Arrays


In [1]:
# creating array using list
l = [1,2,3]


In [2]:
type(l)

list

In [4]:
import numpy as np

In [6]:
arr = np.array(l)

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3])

In [10]:
# creating 2-d arrayor matrix
mat = [[2,2],[3,4]]

In [11]:
mat


[[2, 2], [3, 4]]

In [12]:
type(mat)

list

In [14]:
np.array(mat)

array([[2, 2],
       [3, 4]])

In [16]:
# using np.zeros(shape, type=float)
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros(3,int)

array([0, 0, 0])

In [19]:
np.zeros((4,4), bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [20]:
np.zeros((3,3,3), complex)

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [23]:
# using np.arange(start=0, stop, step=1, dtype=None)

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(10, dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [31]:
np.arange(3,15,3)

array([ 3,  6,  9, 12])

In [32]:
# np.ones()
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# np.linspace()
np.linspace(0,10,2)

array([ 0., 10.])

In [41]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])